name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo cd ~/backend
            sudo git clone https://github.com/ansatjrt/messenger-backend .
            sudo npm install
            sudo npm run build
            sudo pm2 start dist/main.js -- --ENV=production


