name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: SSH deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo rm -r ~/backend
            sudo mkdir ~/backend
            cd ~/backend
            sudo git clone https://github.com/ansatjrt/messenger-backend .
            sudo npm ci
            sudo cp ~/.env.production ~/backend
            sudo NODE_ENV=production node dist/main.js


